name: Rest Assured CI Workflow

on:
  push:
    branches:
      - master  # Replace with your default branch name if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Oracle JDK 17
        uses: oracle-actions/setup-java@v1
        with:
          website: 'oracle.com'  
          release: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    

      - name: Build with Maven
        run: mvn test verify
